# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a7ee38d39a0ccf3dcc4009e8b2dd27a8c42806885bb484790bba9e144b272b0ab7bcddba1df60f66941aa87819f466ba00a813975cb5da498e4669d3a255145

test:
  secret_key_base: 446d007c9ff70de4b975a198c9ceb802f5496e79de0a6e3e64be17eb484bb76f2fd9f8846f08b43babb4086c7b6c48040bccf1b9f13e4f05cb3bad6f7a2219f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
